"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import MyProjectBase
from paramiko import SSHClient, AutoAddPolicy
from netmiko import ConnectHandler
import paramiko # Import paramiko for the policy class

SW_01 = {
    "device_type": "linux",
    "host": "192.168.1.141",
    "username": "tech",
    "password": "Password123",
     "ssh_strict": False,
}



global connection

myssh_client = SSHClient()
myssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
connection = ConnectHandler(**SW_01)

command = "ls -l"
output = connection.send_command(command)
print(f"\nOutput of '{command}':\n{output}")
        
connection.send_command_timing("cd TOES-JTRS-4.1.0")

output = connection.send_command("pwd")
print(output)


# Implementing MyFrame1
class MyProject1MyFrame1( MyProjectBase.MyFrame1 ):
    def __init__( self, parent ):
        MyProjectBase.MyFrame1.__init__( self, parent )
        
        
    def BN_101OnButtonClick( self, event ):
        self.TC_Debug.SetValue('CMD 101')
        command = "./TOES_CONTROL 101"
        output = connection.send_command(command)
        print(f"\nOutput of '{command}':\n{output}")
        self.TC_Debug.SetValue(output)

    def BN_102OnButtonClick( self, event ):
        self.TC_Debug.SetValue('CMD 102')
        command = "./TOES_CONTROL 102"
        output = connection.send_command(command)
        print(f"\nOutput of '{command}':\n{output}")
        self.TC_Debug.SetValue(output)
        
     

    def BN_103OnButtonClick( self, event ):
        self.TC_Debug.SetValue('CMD 103')
        command = "./TOES_CONTROL 103"
        output = connection.send_command(command)
        print(f"\nOutput of '{command}':\n{output}")
        self.TC_Debug.SetValue(output)

        
        
        

# Mandatory wxPython application boilerplate
if __name__ == '__main__':
    app = wx.App(False) # False tells wxPython not to redirect stdout/stderr
    frame = MyProject1MyFrame1(None)
    frame.Show(True)
    app.MainLoop() # Start the application's main event loop
    
